#!/usr/bin/env bash
#MISE description="Compress all png images in public/ to WebP, AVIF, and JPEG XL"
#MISE sources=["src/**/*", "Cargo.lock"]
#MISE outputs={auto=true}

TARGET_DIR=public

# Set quality level (same across all formats)
QUALITY=75
WEBP_EFFORT=6 # 6 is max
AVIF_EFFORT=9
JXL_EFFORT=9

# Find all PNG files in the current directory
for file in "$TARGET_DIR"/**/*.png; do
  [ -e "$file" ] || continue

  base="${file%.png}"
  echo "Converting: $file"

  # Convert to WebP
  vips copy "$file" "${base}.webp[Q=${QUALITY},effort=${WEBP_EFFORT}]"

  # Being a bit less overboard on the formats of images to serve

  # # Convert to AVIF (AV1 compression via libheif)
  # vips copy "$file" "${base}.avif[Q=${QUALITY},compression=av1,effort=${AVIF_EFFORT}]"
  #
  # # Convert to JPEG XL
  # vips copy "$file" "${base}.jxl[Q=${QUALITY},effort=${JXL_EFFORT}]"

done
